### ISSUE TITLE
Strange results

### ISSUE THREAD

**Issue by rebecca0011** [nburrus/stereodemo#1]
I use my own data without calibration data, and got this map.Does the calibration is always required?
<img width="640" alt="222ad2db43f777caccff35d2c20b76c" src="https://user-images.githubusercontent.com/49330159/170447553-17e26d57-1794-4756-b37e-c28286688588.png">

**Comment by nburrus** [comment]
No, the calibration is only useful to get a good scale for the point cloud, but the overall shape should be fine without. Are the results as bad with the other methods? SGBM can sometimes be very noisy, depending on the parameters and the input data. 

Otherwise if you can share the images I'd be curious to try, the only thing I see so far that I haven't really tested is the aspect ratio with height >> width, but that could only be an issue with the deep learning methods that need to stretch the images to the predefined shapes, BM and SGBM will just process the input image untouched.

**Comment by rebecca0011** [comment]
There are unrectified UAV images I used for test. I will use another images and try again. 

Thx!





------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Nicolas ***@***.***&gt;;
Send time:&nbsp;Thursday, May 26, 2022 4:30 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [nburrus/stereodemo] Strange results (Issue #1)





 
No, the calibration is only useful to get a good scale for the point cloud, but the overall shape should be fine without. Are the results as bad with the other methods? SGBM can sometimes be very noisy, depending on the parameters and the input data.
 
Otherwise if you can share the images I'd be curious to try, the only thing I see so far that I haven't really tested is the aspect ratio with height &gt;&gt; width, but that could only be an issue with the deep learning methods that need to stretch the images to the predefined shapes, BM and SGBM will just process the input image untouched.

**Comment by nburrus** [comment]
Ah the images need to be rectified for all methods, otherwise it won’t work.
