### ISSUE TITLE
GUI window is closed

### ISSUE THREAD

**Issue by hogyun2** [nburrus/stereodemo#5]
![image](https://github.com/nburrus/stereodemo/assets/68933951/1379a016-dd5b-43f3-9e32-8a318af07a30)

I have an issue in that the GUI window is closed.
Can you solve it?

**Comment by dgatland** [comment]
@hogyun2 - This might be because the datasets in this repo are stored with Git LFS and if you don't have Git LFS installed the sample images won't clone correctly. (Or at least this was the case for me). 

Try:
1. Delete the cloned repository
2. [Install Git LFS](https://git-lfs.com/)
3. Reclone this repository
4. Run `stereodemo` to view the default image, or eg `stereodemo datasets/oak-d/cycles_*` to show the results for a specific example image

For me, the viewer just shows the two raw images and then an estimated depth map from those images, so I think there might also be some broken features in the viewer perhaps.

**Comment by hogyun2** [comment]
Thank you for the comments. I resolve this issue to set the dataset path!
